---
# Source: deviceshifuchart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: deviceshifu-camera
    workspace_id: a4e315e2-9f35-4e1b-8d00-f55ea725b71f
    device_id: 9cbd82c5-0a72-4363-9949-b3d0b4dc059e
  name: deviceshifu-camera-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: camera-HTTP-driver
    driverImage:
  instructions: |
    instructions:
      "capture":
      "info":
      "stream":
      "move/up":
      "move/down":
      "move/left":
      "move/right":
  telemetries: |
    telemetries:
      capture-test:
        properties:
          instruction: capture
          pushSettings:
            telemetryCollectionService: "test"
      info-test:
        properties:
          instruction: info
          pushSettings:
            telemetryCollectionService: "test"
      stream-test:
        properties:
          instruction: stream
          pushSettings:
            telemetryCollectionService: "test"
---
# Source: deviceshifuchart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-camera
    workspace_id: a4e315e2-9f35-4e1b-8d00-f55ea725b71f
    device_id: 9cbd82c5-0a72-4363-9949-b3d0b4dc059e
  name: deviceshifu-camera-service
  namespace: deviceshifu
spec:
  ports:
  - name: http-service
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deviceshifu-camera-deployment
  type: LoadBalancer
---
# Source: deviceshifuchart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-camera
    workspace_id: a4e315e2-9f35-4e1b-8d00-f55ea725b71f
    device_id: 9cbd82c5-0a72-4363-9949-b3d0b4dc059e
  name: deviceshifu-camera-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-camera-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-camera-deployment
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:v0.64.0-rc1
          name: deviceshifu-http
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-camera-configmap
              mountPath: /etc/edgedevice/config
              readOnly: true
          env:
          - name: EDGEDEVICE_NAME
            value: "deviceshifu-camera-edgedevice"
          - name: EDGEDEVICE_NAMESPACE
            value: "devices"
        - name: camera-python
          image: edgehub/camera-python:v0.0.3
          ports:
            - containerPort: 11112
              protocol: TCP
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-camera"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: IP_CAMERA_ADDRESS
              value: "bj-hikcamera-01.saifai.cn"
            - name: IP_CAMERA_RTSP_PORT
              value: "40554"
            - name: IP_CAMERA_HTTP_PORT
              value: "40080"
            - name: IP_CAMERA_CONTAINER_PORT
              value: "11112"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: IP_CAMERA_USERNAME
              value: "guest"
            - name: IP_CAMERA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: camera-hikvision-secret
                  key: IP_CAMERA_PASSWORD
                  optional: false
          volumeMounts:
      volumes:
        - name: deviceshifu-camera-configmap
          configMap:
            name: deviceshifu-camera-configmap # extraContainer secret
      serviceAccountName: edgedevice-sa
---
# Source: deviceshifuchart/templates/edgedevice.yaml
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  labels:
    app: deviceshifu-camera
    workspace_id: a4e315e2-9f35-4e1b-8d00-f55ea725b71f
    device_id: 9cbd82c5-0a72-4363-9949-b3d0b4dc059e
  name: deviceshifu-camera-edgedevice
  namespace: devices
spec:
  sku: "camera"
  connection: "Ethernet"
  address: "0.0.0.0:11112"
  protocol: "HTTP"
