# 摄像头设备的凭据 Secret，包含用户名和密码 (基本安全：Opaque 类型)
apiVersion: v1
kind: Secret
metadata:
  name: camera-credentials
  namespace: default   # 可以是 devices 等命名空间，根据实际情况调整
type: Opaque
data:
  # 将 'admin' 和 'P@ssw0rd' 分别替换为实际摄像头的用户名和密码，并使用 base64 编码
  username: YWRtaW4=           # "admin" 经 base64 编码后的字符串
  password: UEBzc3cwcmQ=       # "P@ssw0rd" 经 base64 编码后的字符串
---
# 摄像头 DeviceShifu 部署，将凭据通过环境变量提供给驱动容器
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviceshifu-camera
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-camera
  template:
    metadata:
      labels:
        app: deviceshifu-camera
    spec:
      # 若需要将此 Pod 调度到特定节点（例如边缘节点），可在此处添加 nodeSelector 或 nodeName
      containers:
        # 主容器：Shifu HTTP 接口容器
        - name: deviceshifu-http
          image: edgehub/deviceshifu-http:latest
          # ...此处省略其他配置，例如端口、挂载配置等...
        # 摄像头驱动容器：实际与摄像头设备交互的驱动
        - name: camera-driver
          image: edgehub/camera-python:v0.0.1   # Shifu 提供的摄像头驱动镜像
          ports:
            - containerPort: 11111              # 摄像头驱动容器对外提供服务的端口
          env:
            - name: IP_CAMERA_ADDRESS
              value: "192.168.1.100"            # 摄像头IP地址示例
            - name: IP_CAMERA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: camera-credentials
                  key: username
            - name: IP_CAMERA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: camera-credentials
                  key: password
            - name: IP_CAMERA_CONTAINER_PORT
              value: "11111"                    # 驱动容器内部使用的端口（Shifu文档默认11111）
      # 如果使用 KubeEdge/OpenYurt 等，可在此处指定 nodeName 将驱动部署到边缘节点
      # nodeName: edge-node-1
