apiVersion: batch/v1
kind: Job
metadata:
  name: shifu-demo-install
spec:
  template:
    spec:
      containers:
        - name: shifu-demo-install
          image: ubuntu:latest
          command:
            - "bash"
            - "-c"
            - "curl -sfL https://raw.githubusercontent.com/Edgenesis/shifu/main/test/scripts/shifu-demo-install.sh | sudo sh -"
      restartPolicy: Never
