---
# Source: telemetryservicechart/templates/telemetryservice.yaml
apiVersion: shifu.edgenesis.io/v1alpha1
kind: TelemetryService
metadata:
  labels:
    id: 513d36f5-4c49-488e-ac4f-6e702359ff6e
    workspace_id: a4e315e2-9f35-4e1b-8d00-f55ea725b71f
    app: test
  name: test
  namespace: devices
spec:
  telemetryServiceEndpoint: http://telemetryservice.shifu-service.svc.cluster.local
  serviceSettings:
    MQTTSetting:
      MQTTServerAddress: 1.1.1.1:8888
      MQTTTopic: /test/test
